addr = "0.0.0.0"
port = 5000

[s3]
bucket = "local-bucket"
region = "us-east-1"
client_id = "minioadmin"
client_secret = "minioadmin"
host = "http://172.18.0.2:9000"

[local_fs]
root_path = "/app/local-fs"

[sqlite]
s3_object_path = "app.db"

[smtp]
host = "172.18.0.3"
port = 1025
use_tls = false
username = ""
password = ""
from_email = "noreply@example.com"

[pipes]
api_base_url = "http://localhost:11434/v1"
api_key = ""
models = [
    { id = "qwen3:32b", name = "Qwen 3 32B" },
]