[serve]
port = 8083

[watch]
ignore = ["dist"]

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:5003/api/"

[[proxy]]
rewrite = "/api/ws"
backend = "ws://localhost:5003/api/ws"
ws = true

[[proxy]]
rewrite = "/config.json"
backend = "http://localhost:8093/config.json"
