[serve]
port = 8080

[watch]
ignore = ["dist"]

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:3001/api/"

[[proxy]]
rewrite = "/api/ws"
backend = "ws://localhost:5003/api/ws"
ws = true

[[proxy]]
rewrite = "/config.json"
backend = "http://localhost:8090/config.json"
