server {
    listen 80;
    server_name localhost;

    location /config.json {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache";
    }
}
